name: "Build RPM Packages"

on:
  workflow_dispatch:
    inputs:
      mcpp_version:
        description: "The MCPP version to build"
        required: false

jobs:
  build:
    name: "Build for ${{ matrix.distribution }}-${{ matrix.arch }}"
    runs-on: ${{ matrix.arch == 'aarch64' && 'ubuntu-24.04-arm' || 'ubuntu-24.04' }}
    strategy:
      matrix:
        include:
          - distribution: rhel9
            arch: x86_64

          - distribution: rhel9
            arch: i686

          - distribution: rhel9
            arch: aarch64
    steps:
      - name: Check out repository
        uses: actions/checkout@v4
        with:
          path: mcpp

      - name: Build Docker Image
        run: docker build --pull -f mcpp/packaging/rpm/docker/${{ matrix.distribution }}/Dockerfile -t mcpp-rpm-package-builder "$GITHUB_WORKSPACE/mcpp"

      - name: Build RPM Packages
        run: |
          docker run --rm \
            -v "$GITHUB_WORKSPACE:/workspace" \
            -e MCPP_VERSION="${{ inputs.mcpp_version }}" \
            -e GIT_TAG="${{ github.ref_name }}" \
            -e RPM_TARGET_ARCH="${{ matrix.arch }}" \
            mcpp-rpm-package-builder /workspace/mcpp/packaging/rpm/build-package.sh

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rpm-packages-${{ matrix.distribution }}-${{ matrix.arch }}
          path: |
            build/RPMS/*
